# Vektoren

* Im vergleich zu normalen Zahlen (Skalare) sind Vektoren meistens Objekte mit mehreren elementen.


* Für unsere Zwecke gehen wir nur von Vektoren aus die Skalare als Elemente haben.


* Beispiel für einen 3-dimensionalen Vektor $v_z$ = [2, 5, 1] oder $v_z$ = (2, 5, 1)

* Wir unterscheiden zwei Typen von Vektoren: Spalten- und Zeilenvektor
* Zeilenvektoren schreiben wir horizontal und Spaltenvektoren vertikal
* Durch transponieren wandelt man Zeilen in Spaltenvektoren und umgekenrt.
* $v_z'$ = $v_s \quad$ und $\quad v_s' = v_z$ wobei $'$ für das transponieren steht

$$
v_s = \left(\begin{matrix}2 \\ 5 \\ 1\end{matrix}\right) \quad v_z = \left(\begin{matrix} 2 &5 &1\end{matrix} \right)
$$

* Vor allem in der Physik werden Vektoren als Pfeile in einem Koordinatensystem dargestellt.
* So ein Pfeil hat 3 wichtige Eigenschaften die ihn definieren:
 - Richtung
 - Betrag
 - Länge (= Anzahl Elemente)
 
Als Beispiel für einen Vektor kann man Windgeschwindigkeit nehmen
 - Länge = 3 (Weil wir im 3-dimensionalen Raum sind)
 - Richtung = Nord-West (als Beispiel)
 - Betrag = 45 km/h
 
 
Im Gegensatz Dazu sind Dinge wie *Temperatur* oder *Franken* keine Vektoren, denn sie besitzen keine
Richtung.

## Addition von Vektoren

Vektoren gleicher dimension können addiert werden, dies geschieht elementweise.

$$
\left(\begin{matrix}x_1 \\ x_2 \\ x_3\end{matrix}\right) + \left(\begin{matrix}y_1 \\ y_2 \\ y_3\end{matrix}\right) = \left(\begin{matrix}x_1+y_1 \\ x_2+y_2 \\ x_3+y_3\end{matrix}\right)
$$


Und als ein konkretes Beispiel


$$
\left(\begin{matrix}2 \\ 5 \\ 1\end{matrix}\right) + \left(\begin{matrix}1 \\ -2 \\ 0\end{matrix}\right) = \left(\begin{matrix}2+1 \\ 5-2 \\ 1+0\end{matrix}\right) = \left(\begin{matrix}3 \\ 3 \\ 1\end{matrix}\right)
$$


## Multiplikation mit Skalar (=Zahl)

Wird ein Vektor mit einem Skalar multipliziert, so geschieht das ebenfalls elementweise.
$$
a \cdot \left(\begin{matrix}x_1 \\ x_2 \\ x_3\end{matrix}\right) = \left(\begin{matrix}a\cdot x_1 \\ a\cdot x_2 \\ a\cdot x_3\end{matrix}\right)
$$


Mit folgendem Zahlenbeispiel


$$
2 \cdot \left(\begin{matrix}2 \\ 5 \\ 1\end{matrix}\right) = \left(\begin{matrix}4 \\ 10 \\ 2\end{matrix}\right)
$$

# Aufgaben

a) Skizziere auf ein Blatt die zwei Vektoren **$a$** = (3, 1),  **$b$** = (2, 2) und **$c$** = (-4, 0)

b) Skizziere $a$ + $b$

c) Skizziere $a + b + c$

d) Skizziere $c - b$

e) Skizziere $2\cdot a$

f) Skizziere $3\cdot a$

g) Skizziere $(-1)\cdot b$

h) Löse aufgaben b) bis g) mit Julia

In [12]:
# In Julia heissen Vektoren 'Arrays' und werden folgendermassen definiert: A = [1, 2, 3]
# Definiere nun die Vektoren a, b, und c in Julia und Löse die vorhergehenden Aufgaben mit Julia.
# Um Code auszuführen musst du Shift+Enter drücken.
# Versuche den "Code" für die Aufgabe zu erraten... :)
# Resultate können mit @show(...) ausgegeben werden

# Definition von Arrays
vec_1 = [1, 2, 3]
vec_2 = [2, 4, 0]

# Definition von Skalaren
foo = 3
bar = 6

@show(vec_2)
@show(foo + bar);


##############################################
# Setze deinen Code unterhalb dieser Zeile ein



vec_2 = [2,4,0]
foo + bar = 9


# Inneres Produkt
* Das Innere Produkt zwischen zwei Vektoren $a$ und $b$ ist so DEFINIERT, dass es proportional zum cos() des Winkels zwischen den beiden Vektoren ist.

* Das Vektorprodukt nimmt also zwei Vektoren und gibt einen Skalar zurück.





** Diese Zahl hat folgende nützliche Eigenschaften:**
* Das Vektorprodukt ist = 0, wenn die Vektoren senkrecht zueinander stehen.
* Das Vektorprodukt ist > 0, falls der Winkel zwischen $a$ und $b$ kleiner als 90 Grad ist.
* Das Vektorprodukt ist < 0, falls der Winkel zwischen $a$ und $b$ grösser als 90 Grad ist.

* Das Innere Produkt zwischen zwei Vektoren schreibt sich $a \cdot b$, also mit einem "Punkt" zwischen zwei Vektoren.
* Es gilt folgende Definition für Vektoren der Länge n

$$ a \cdot b = \sum_{i=1}^n{a_i\: b_i} = a_1 b_1 + a_2b_2 + \dots + a_n b_n$$

* Der Betrag eines Vektors **||a||** misst dessen "Grösse", sprich wie lang der Pfeil ist.
* Der Betrag eines Vektors wird als das Innere Produkt des Vektors mit sich selbst berechnet:

$$ ||a|| = \sqrt{a \cdot a} = \sqrt{\sum_{i=1}^n{a_i \: a_i}}$$

In [34]:
# AUFGABEN
##########
# In Julia heisst die Funktion zur Berechnung des Inneren Produkts
# "dot(vec_1, vec_2)", gemäss dem Punkt in der Notation.
# Der Betrag eines Vektors berechnet sich mit der Funktion "norm()"
# Finde einen Wert für c[2] so dass der Vektor c senkrecht auf a 
# und auf b steht.

a = [1, 2, 3]
b = [2, 2, 0]

c = [-6, 0, -2]

3-element Array{Int64,1}:
 -6
  0
 -2

In [ ]:
# AUFGABEN
##########
# Du hast eine Liste mit Esswaren die und deren kcal/100g.
# Apfel:50 Salat:35, Fleisch:250, Reis:130, Nudeln:160
# Yoghurt:95, Schoggi:550
# Stell dir ein Menu zusammen (z.B. 100g Apfel, 400g Fleisch etc.)
# und berechne die Gesamtkalorienmenge mit hilfe des Skalarprodukts.


In [35]:
# AUFGABE
#(alle Angaben in Metern, falls nichts anderes erwähnt)
#########################################################

# Willhelm Tell steht mit seiner Armbrust parat.
# Seine Finger befindet sich am Abzug, und die Pfeilspitze
# am Punkt [0.5, 0.0, 1.7]. Walterli steht mit Apfel auf
# dem Kopf ebenfalls parat. Die Koordinaten des Apfels
# sind [10.5, 22.0, 1.5]. Wie gross ist die Distanz zw.
# Pfeilspitze und Apfel?




# Bonusaufgabe:
###############
# Angenommen der Apfel hat einen Radius von
# ca. 5 cm, mach eine Abschätzung für den Spielraum den
# Tell hat um nicht Walterli in den Kopf zu treffen.
# D.h. um welchen Winkel darf er sich vertun ohne seinen
# Sohn zu verletzen.

# Tipp 1: Für zwei Vektoren a und b und den Winkel w zwischen
# ihnen gilt:
# cos(w) = a / ||a|| . b / ||b||

# Tipp 2: Um von cos(w) auf den Winkel w zu kommen gibt es
# in Julia die Funktion acos(). Also acos(cos(w)) = w.

# Tipp 3: Der Winkel w ist dann in radian, um auf grad zu
# zu kommen rechnet man radian / pi * 180

In [3]:
using Plots
plotly()

function show_data(X)
    scatter(X[ipos,1], X[ipos,2], color=:blue, label="positive", marker=(:circle, 8, stroke(0, :blue)))
    scatter!(X[ineg,1], X[ineg,2], color=:red, label="negative", marker=(:circle, 8, stroke(0, :red)))
end

function show_theta!(theta)
    plot!([0,theta[1]],[0, theta[2]], color=:black, width=2, label="theta")
end

function show_predicted_labels!(X, theta)
    yhat = sign(X * theta)
    
    ipos = yhat .== 1.0
    ineg = yhat .== -1.0
    
    accuracy = mean(yhat .== y) * 100
    println("Classification accuracy: $accuracy %")
    
    scatter!(X[ipos,1], X[ipos,2], color=:blue, label="predicted-pos", m=(:circle, 3, stroke(0)))
    scatter!(X[ineg,1], X[ineg,2], color=:red, label="predicted-neg", m=(:circle, 3, stroke(0)))
end

X = readcsv("data_ex1.csv")

nPerClass = floor(Int, size(X, 1)/2)
ipos = 1:nPerClass
ineg = nPerClass+1:2nPerClass

y = ones(Int64, 2*nPerClass)
y[nPerClass+1:2*nPerClass] *= -1

show_data(X)

In [15]:
# Machine Learning Aufgabe!
###########################

# Es wurden 2 dimensionale Daten geladen und in
# die Variable X gespeichert. X besteht aus 42(!)
# Datenpunkten und jeder Datenpunkt hat zwei
# Koordinaten.

# Je die Hälfte der Datenpunkte gehört
# zu Klasse positiv (blau), die andere zur Klasse negativ (rot).
# Die Information zur Klasse ist in der Variable y hinterlegt.
# D.h. y ist ein Array mit 42 Zahlen. +1 für die positive Klasse
# und -1 für die negative Klasse.

# Auch wenn die Daten als blaue oder rote Punkte dargestellt sind,
# kannst du dir sie als Vektoren vorstellen. Diese Vektoren haben
# den Schwanz bei [0,0] und die Spitze beim jeweiligen (blauen oder roten)
# Kreis.

# Das Ziel ist nun ein Modell zu finden, welches die blauen von den 
# roten Punkten unterscheiden kann. Und zwar mit Hilfe des Skalarprodukts.



# a) Finde einen Vektor 'theta' so dass:
# theta . x > 0 für alle blauen Datenpunkte
# theta . x < 0 für alle roten Datenpunkte.
# Verändere die Werte in theta so dass du 100 % classification
# erreichst. Die Grafik zeigt die eigentlichen Werte und die 
# Werte die durch das Modell

# b) Erkläre in Worten was für einen Zusammenhang du zwischen
# dem Vektor theta und den Resultaten deines Modells du erkennen
# kannst.

# c) Falls in b) nicht beantwortet: Was spielt das Skalarpodukt
# bei diesem Modell für eine Rolle?

 

theta = [1, -1]

show_data(X)
show_predicted_labels!(X, theta)
show_theta!(theta)

Classification accuracy: 73.80952380952381 %


# Lineare Gleichungssysteme

* Wenn mehr als eine Unbekannte vorkommen, müssen auch mehrere Gleichungen definiert werden, da sonst das Problem unbestimmt ist.

* Beispiel: Die folgende Gleichung mit zwei Unbekannten hat unendlich viele Lösungen:

$$ x_1 + x_2 = 10$$

$$ 1 + 9 = 10$$
$$ 2 + 8 = 10$$
$$ \vdots $$
$$   $$
$$ 5 + 5 = 10$$

* Erst durch zusätzliche Bedingungen wird eine eindeutige Lösung bestimmt.
* Es wird erwartet dass $x_1$ und $x_2$ so gefunden werden, dass alle Bedingungen erfüllt werden.
* Es gibt also einen Zusammenhang zwischen den Gleichungen, ein Gleichungssystem.

$$ \begin{align}
x_1 + x_2 &= 10\\
x_1 - 3x_2 &= -2\\
\end{align}$$

In der allgemeinen Form:

$$ \begin{align}
a_{11} x_1 + a_{12} x_2 &= y_1\\
a_{21} x_1 + a_{22} x_2 &= y_2\\
\end{align}
$$

Finde $a_{ij}$ und ${y_i}$ für obiges Gleichungssystem


# Lösungsmethoden für Gleichungssysteme
Alle Lösungsmethoden beziehen sich auf das Gleichungssystem

$$ \begin{align}
x_1 + x_2 &= 10\\
x_1 - 3x_2 &= -2\\
\end{align}$$



## 1. Gleichsetzen
Zum Beispiel beide Gleichungen oben nach $x_1$ auflösen und diese gleichsetzen.
$$\begin{align}
x_1 &= 10 - x_2\\
x_1 &= -2 + 3x_2\\
\end{align}$$


$$\begin{align}
10 - x_2 &= -2 + 3x_2\\
12 - x_2 &= 3x_2\\
12 &= 4x_2\\
3 &= x_2\\
\end{align}$$





## 2. Einsetzen
Alternativ kann auch nach einer Variablen aufgelöst werden und diese dann in die anderen Formeln einsetzen.

$$ x = 10 - y$$


Den gefundenen Ausdruck für $x$ jetzt in die zweite Gleichung $x - 3y = -2$ einsetzen.


$$
\begin{align}
10 - y - 3y &= -2\\
10 -4y &= -2\\
-4y &= -12\\
-y &= -3\\
y &= 3\\
\end{align}$$

## 3. Eliminationsverfahren
Die gebräuchlichste und effizienteste Methode ist das Eliminationsverfahren. Dabei werden Gleichungen miteinander addiert oder subtrahiert, so dass dadurch Variablen sich gegenseitig rauskürzen. Wenn man im oberen Beispiel von der oberen Gleichung die Untere abzieht, erhält man

$$\begin{align}
4y &= 12\\
y &= 3
\end{align}$$

Das Eliminationsverfahren wird auch von Computern verwendet um Gleichungssysteme zu lösen und skaliert sehr gut für den Fall von vielen Gleichungen und Unbekannten.


$$ a_{11}x_1 + a_{12}x_2 + a_{13}x_3 = y_1$$
$$ a_{21}x_1 + a_{22}x_2 + a_{23}x_3 = y_2$$
$$ a_{31}x_1 + a_{32}x_2 + a_{33}x_3 = y_3$$

In [3]:
function solver1(X, y)
    inv(X' * X) * X' * y
end

function solver2(X, y)
    X \ y
end

solver2 (generic function with 1 method)

In [5]:
#              Getraenk, Salat, Menu I, Pizza   Total_CHF
##########################################################
# Montag     :     4        2      3       1    |   90.0       
# Dienstag   :     2        0      2       1    |   55.0
# Mittwoch   :     5        5      0       2    |   86.0
# Donnerstag :     1        1      1       0    |   25.0
# Freitag    :     1        4      2       2    |   95.5


item_price = [3.5, 6.5, 15.0, 18.0]
A = [4 2 3 1; 2 0 2 1; 5 5 0 2; 1 1 1 0; 1 4 2 2]

y = A * item_price
@show(y);
A

y = [90.0,55.0,86.0,25.0,95.5]


5×4 Array{Int64,2}:
 4  2  3  1
 2  0  2  1
 5  5  0  2
 1  1  1  0
 1  4  2  2

In [7]:
@time solver1(A, y)

  0.000049 seconds (23 allocations: 4.297 KB)


4-element Array{Float64,1}:
  3.5
  6.5
 15.0
 18.0

In [12]:
@time solver2(A, y)

  0.000105 seconds (87 allocations: 72.609 KB)


4-element Array{Float64,1}:
  3.5
  6.5
 15.0
 18.0

In [14]:
(A*theta - A*theta_real) ./ y

LoadError: LoadError: UndefVarError: theta not defined
while loading In[14], in expression starting on line 1

solver2 (generic function with 1 method)

4-element Array{Float64,1}:
 0.243983
 0.844875
 0.694701
 0.799641